name: Angular Build & Deploy page
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy la page Angular 
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@master
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        deploy_branch: gh-pages
        angular_dist_build_folder: dist
