name: Discord Event Message
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: send message on Discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        args: Un ${{ github.event_name }} à été lancé par ${{ github.actor }} sur la branche ${{ github.ref }}.
