name: JeremyCI

on:
  push:
    branches: [ jeremy ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: npm install and npm run build
        run: |
          npm install
          npm run start
