name: Angular Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy la page Angular 
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.3.1
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: prod
        base_href: /GitHub-Exporation/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/GitHub-Exporation
