name: Sullivan Test
on:
  push:
    branches: [ sullivan ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        args: Un ${{ github.event_name }} à été fait sur la branche ${{ github.ref }}.
